### ISSUE TITLE
battery power

### ISSUE THREAD

**Issue by maddron** [xyzroe/Zintercom#11]
hey!
When powered by a battery, the device must always be in sleep mode. But somehow it turned out that the device immediately responded about changing the mode (never, once, drop). It was very convenient, even despite the increased battery consumption. 
After replacing the battery, the device is constantly in sleep mode (as per the instructions). 

Is there a way to put it into a state so that it responds to the mode change immediately? Or it was a bug or smth?

**Comment by xyzroe** [comment]
Hello!
As far as I know, the device may not go into sleep mode if reporting is not configured / the interview has not completely passed. Perhaps you have had one of these cases.

In sleep mode, a change in the reporting interval is available, and it seems to me that if you set it to 0 minutes, then it will not go into sleep mode.
