### ISSUE TITLE
Can't repair Zintercom

### ISSUE THREAD

**Issue by DejavuDmitry** [xyzroe/Zintercom#12]
After deleting device from z2m I just can't pair it again.
I was trying to press changing mode button for more than 5 seconds (didn't work), also resetting the power for 5 times, nothing changes.
What I must do for positive result?
Thanks.

**Comment by xyzroe** [comment]
There are only two ways to reset the device to factory settings. You have tried both.
You can also try to reflash the device, but this is unlikely to help.

There may be a problem with your network, so the device is not connecting.
