### ISSUE TITLE
Problems with converter

### ISSUE THREAD

**Issue by brutevinch** [xyzroe/Zintercom#13]
In dev version zigbee2mqtt we get this:
zigbee  | Zigbee2MQTT:error 2023-12-19 13:31:01: Failed to load external converter file 'converters/DIYRuZ_Zintercom.js' (Cannot read properties of undefined (reading 'presets'))
zigbee  | Zigbee2MQTT:error 2023-12-19 13:31:01: Probably there is a syntax error in the file or the external converter is not compatible with the current Zigbee2MQTT version
zigbee  | Zigbee2MQTT:error 2023-12-19 13:31:01: Note that external converters are not meant for long term usage, it's meant for local testing after which a pull request should be created to add out-of-the-box support for the device

looks like need some fixes.

**Comment by xyzroe** [comment]
https://xyzroe.cc/ZigUSB/
Have you tried new one?

**Comment by xyzroe** [comment]
Sorry,

**Comment by xyzroe** [comment]
https://www.zigbee2mqtt.io/devices/DIYRuZ_Zintercom.html

@brutevinch Zintercom should work without any converter.

**Comment by brutevinch** [comment]
wow! thank you. ill check it
