### ISSUE TITLE
Question: Why no opening switch in the module?

### ISSUE THREAD

**Issue by SAOPP** [xyzroe/Zintercom#5]
Hi!

I'm playing with your module right now. Thanks for your work!

But I immediately had a question after connecting, why is the firmware not equipped with a switch that would send a signal to open?

Having looked at the diagram, I could not draw a conclusion for myself, I'm wondering why such an implementation is now, and what is missing for the opportunity to add this switch?

Thanks.

**Comment by xyzroe** [comment]
Hey!
The opening is realized by setting one of the operating modes (except Never).
If you need a switch you can add it to an external converter or create a virtual switch based on the operating mode in your smart home system.

**Comment by SAOPP** [comment]
Hey, thanks for an answer. So, I understand correctly, if during a incoming call, I switch from `never` mode to (for example) `once` or `always` - will the module open the door? Right?

**Comment by xyzroe** [comment]
Yes.  You are absolutely right

**Comment by SAOPP** [comment]
Thanks homie! Have a nice day!

**Comment by SAOPP** [comment]
Btw, I almost forgot, I'll write it down here, ideally, the following things are missing:

1. this is a switch opening out of the box in the firmware
2. these are the possibilities of soldering an external button on the board, for opening, for example, when there is a need to make button outside of the case or connect this button to existing button in intercom phone

I hope this will appear in the next versions of the firmware and the module itself, thanks in any case homie, a cool project, in particular, catch five for zigbee kehd. ;)

**Comment by SAOPP** [comment]
And I immediately came up with another 1 point:

3. this is the addition of a LED that will notify about the current operating mode of the intercom

This option, but it is very convenient in everyday life. I think it's all from my side now.

I would be glad to hear any comments on the above points, thank you.

**Comment by xyzroe** [comment]
1. This can be done with an external converter.  
2. it is possible, see X4.  pin 1.2.  
3. The LED displays the current mode anyway.  Read the description.

**Comment by SAOPP** [comment]
1. ok
2. I will see it, thanks
3. yes, but when I switch modes, my led is silent at all, and I'm talking about displaying the led status in real time

**Comment by xyzroe** [comment]
3. It shows mode right after change. Not during idle. 
Feel free to make PR 😀
