### ISSUE TITLE
Change the organization's logo

### ISSUE THREAD

**Issue by xyzroe** [xyzroe/Zintercom#9]
Hello @kirovilya, @nurikk, @G1K 

Could you change the organization’s logo? Because the Russian flag, and even more so with the military symbol, is currently unacceptable on it all over the world.

if this is unacceptable for you - please transfer this repository back to me as the original author, because I am forced to leave the organization with such symbols on logo.

**Comment by G1K** [comment]
I'm not the owner of the organization, but I don't mind. However, I do not understand of course what to replace the letter, which in this direction symbolizes zigbee.

**Comment by xyzroe** [comment]
Probably to avoid doublethink use the whole word Zigbee or short Zig

Or we can use bee in logo instead of letter?

**Comment by kirovilya** [comment]
Hello. I didn't think that the Zigbee symbol would have a negative meaning.
The original name DiyRuZ meant the Russian-speaking DIY-Zigbee-community. And at the time of the appearance, the picture meant exactly that and nothing else.
I understand that now this combination will be a trigger for some users.
Alternatively, I can remove the coloring, leaving the rest of the elements the same.
![DiyRuZ](https://user-images.githubusercontent.com/8360230/174661168-b8ca47de-6cac-441e-b086-6639c5009d8b.png)

**Comment by xyzroe** [comment]
But given that this symbol is used in military propaganda, it should be replaced.

It's not about triggering some users, it's about if you call the community **_Russian-speaking_**, let's remove the flag - make the logo really politically **neutral**.
Even in gray, this is the same flag - the **aggressor** state.

Why not use a bee, like one of the well-known software, but in combination with DIY?
![diyruz](https://user-images.githubusercontent.com/6440415/174665015-67ca9862-b704-4e10-b422-f7c03acd9c0b.png)

**Comment by nurikk** [comment]
Agree on point that aggressor state flag should be taken down. But not agree on letter z, it's taken straight away from [Zigbee Alliance Trademark and Logo Usage Guidelines and Terms](https://zigbeealliance.org/wp-content/uploads/2019/12/Zigbee-Alliance-Trademark-and-Logo-Usage-Guidelines-and-Terms.pdf). Don't let this fuckers to take away letter z from you, even if they're using it for propaganda.

The proposed logo above is already good enough :)

**Comment by xyzroe** [comment]
If we refer to the Zigbee Alliance Trademark and Logo Usage Guidelines and Terms, let's use the original logo. Without any political elements.
![1](https://user-images.githubusercontent.com/6440415/174691908-9c228969-d0de-4d08-b8ba-4b26482d6a6a.png)

**Comment by kirovilya** [comment]
how about a flatter logo?
![DIYRuZ](https://user-images.githubusercontent.com/8360230/174730518-800d24c0-eed3-4ec6-a167-8e108b831005.png)

**Comment by xyzroe** [comment]
Thank you all for the objective assessment of what is happening!

**Comment by kirovilya** [comment]
Other community members wrote to me that they were outraged by the change in logo and transition to neutral colors, citing political motives for such a decision. I'm bringing back the old logo.

**Comment by nurikk** [comment]
> Other community members wrote to me that they were outraged by the change in logo and transition to neutral colors, citing political motives for such a decision. I'm bringing back the old logo.

Who are this members? Do the contribute in open source Zigbee?

**Comment by nurikk** [comment]
There are 4 members  in this  organisation, I don’t see any outrage in this conversation 


![D4149758-BC84-471B-BE1A-20E669F36F56](https://user-images.githubusercontent.com/1525421/174957630-4ca60a0b-d47d-44a5-bc55-2cfdaed69548.jpeg)

**Comment by kirovilya** [comment]
not the authors of the firmware, but those who use these firmware, make devices with them.

**Comment by xyzroe** [comment]
If you want to politicize on GitHub, please transfer the Zintercom repo to my account, please, and stay with your logo rag.

**Comment by kirovilya** [comment]
@xyzroe I gave admin rights - now you can transfer the repository to yourself. I can't do it myself

**Comment by xyzroe** [comment]
> not the authors of the firmware, but those who use these firmware, make devices with them.

 Ilya, you act like a chick who gives opinion twice a day, yesterday you had no contradictions with changing logo.

 And for users who do not even contribute to open source software, but want to dictate the rules - start with your contribution, and then tell others how to act.

**Comment by xyzroe** [comment]
@nurikk Thanks for being objective.

**Comment by kolbertv** [comment]
> If you want to politicize on GitHub, please transfer the Zintercom repo to my account, please, and stay with your logo rag.

Ты сам политикой занимаешься в гитхабе судя по твоему аккаунту. Так что  не надо других обвинять.

**Comment by xyzroe** [comment]
> > If you want to politicize on GitHub, please transfer the Zintercom repo to my account, please, and stay with your logo rag.
> 
> Ты сам политикой занимаешься в гитхабе судя по твоему аккаунту. Так что не надо других обвинять.

I forgot to ask you, pigdog.

**Comment by kolbertv** [comment]
> > > If you want to politicize on GitHub, please transfer the Zintercom repo to my account, please, and stay with your logo rag.
> > 
> > 
> > Ты сам политикой занимаешься в гитхабе судя по твоему аккаунту. Так что не надо других обвинять.
> 
> I forgot to ask you, pigdog.

Поросенок микола, не бомби.)

**Comment by xyzroe** [comment]
> > > > If you want to politicize on GitHub, please transfer the Zintercom repo to my account, please, and stay with your logo rag.
> > > 
> > > 
> > > Ты сам политикой занимаешься в гитхабе судя по твоему аккаунту. Так что не надо других обвинять.
> > 
> > 
> > I forgot to ask you, pigdog.
> 
> Поросенок микола, не бомби.)

what a manner to come to where no one called and start to spread their orders?
